name: atm_env
channels:
  - ranaroussi
  - anaconda
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - appnope=0.1.0
  - asn1crypto=1.0.1
  - attrs=19.2.0
  - backcall=0.1.0
  - bleach=3.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cffi=1.12.3
  - chardet=3.0.4
  - click=7.0
  - cryptography=2.7
  - dash=1.3.0
  - dash-core-components=1.2.0
  - dash-html-components=1.0.1
  - dash-renderer=1.1.0
  - dash-table=4.3.0
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - flask=1.1.1
  - flask-compress=1.4.0
  - future=0.18.0
  - icu=64.2
  - idna=2.8
  - importlib_metadata=0.23
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - itsdangerous=1.1.0
  - jedi=0.15.1
  - jinja2=2.10.3
  - joblib=0.14.0
  - json5=0.8.5
  - jsonschema=3.1.1
  - jupyter_client=5.3.3
  - jupyterlab=1.1.4
  - jupyterlab-plotly-extension=1.0.0
  - jupyterlab_server=1.0.6
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.0
  - libcxxabi=9.0.0
  - libffi=3.2.1
  - libgfortran=4.0.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libsodium=1.0.17
  - libuv=1.32.0
  - llvm-openmp=9.0.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - more-itertools=7.2.0
  - multitasking=0.0.9
  - nb_conda_kernels=2.2.2
  - nbconvert=5.6.0
  - ncurses=6.1
  - nodejs=12.11.1
  - notebook=6.0.1
  - numpy=1.17.2
  - openssl=1.1.1c
  - pandas=0.25.1
  - pandas-flavor=0.1.2
  - pandoc=2.7.3
  - parso=0.5.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.2.3
  - plotly=4.1.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.4.2
  - pyjanitor=0.18.2
  - pyopenssl=19.0.0
  - pyrsistent=0.15.4
  - pysocks=1.7.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.3
  - pyyaml=5.1.2
  - pyzmq=18.1.0
  - readline=8.0
  - requests=2.22.0
  - retrying=1.3.3
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=41.4.0
  - six=1.12.0
  - sqlite=3.30.1
  - testpath=0.4.2
  - tk=8.6.9
  - tornado=6.0.3
  - traitlets=4.3.3
  - urllib3=1.25.6
  - werkzeug=0.16.0
  - wheel=0.33.6
  - xz=5.2.4
  - yaml=0.1.7
  - yfinance=0.1.45
  - zeromq=4.3.2
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - ipywidgets==7.5.1
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.0.0
    - jupyter-core==4.6.0
    - nbformat==4.4.0
    - pandocfilters==1.4.2
    - qtconsole==4.5.5
    - terminado==0.8.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1

